Add blog post for restic 0.17.1
restic/restic.net pull request #40
Opened 2024-09-02 19:59 UTC by MichaelEischer

2024-09-02 20:09 UTC, rawtaz requested changes

2024-09-02 20:09 UTC, rawtaz commented on content/blog/restic-0.17.1-released.md
> +This release contains various bugfixes and small enhancements. The most important are the following:
```suggestion
This release contains various bug fixes and small enhancements. The most important ones are the following:
```

2024-09-02 20:09 UTC, rawtaz commented on content/blog/restic-0.17.1-released.md
> +- The backup command now always stores files and directories even if some metadata could not be retrieved.
```suggestion
- The backup command now also stores files and directories for which some metadata could not be retrieved.
```

2024-09-02 20:33 UTC, MichaelEischer commented on content/blog/restic-0.17.1-released.md
> +This release contains various bugfixes and small enhancements. The most important are the following:
changed. Thanks!

2024-09-02 20:33 UTC, MichaelEischer commented on content/blog/restic-0.17.1-released.md
> +- The backup command now always stores files and directories even if some metadata could not be retrieved.
also changed.

2024-09-05 19:55 UTC, rawtaz approved these changes

2024-09-05 19:55 UTC, merged